#!/bin/bash

echo "Entrez le nom de l'utilisateur a supprimer : "
read name

kill `ps aux | grep sshd. | grep -v root | grep $name | cut -d '.' -f1 | rev | cut -d ' ' -f3 | rev`
passwd -l $name
killall -KILL -u $name
crontab -r -u $name
userdel -r $name
echo "
Done."
