#!/bin/bash

clear

nop=0
while [ $nop == 0 ]
do
echo "
########## Le scrip du petit codeur ##########

0. Exit :
1. Delete the cache :
2. Push :
3. Run 42sh :
4. Who is your best friend ?
5. Kill bad files :
6. Joue avec moi :
"

read var

if [ $var -ne 0 ] && [ $var -ne 1 ] && [ $var -ne 2 ] && [ $var -ne 3 ] &&
[ $var -ne 4 ] && [ $var -ne 5 ] && [ $var -ne 6 ] && [ $var -ne 101 ];
then
echo "Not a valide choice

See you."
read
clear
break
fi

if [ $var == 0 ];
then
echo "See you"
clear
exit 0

elif [ $var -eq 1 ];
then
echo "Load...
"
find ~ -name "*.42_cache_bak" -print -delete
echo "
Done :) "
read
clear

elif [ $var -eq 2 ];
then
read -p "entrer le chemin a partir de ce repertoir: " path
cd $path
git add .
git commit -m "done"
git push
echo "
Push Done

ls-files :
"
git ls-files
echo "
Done"

read
clear

elif [ $var -eq 3 ];
then
sh ~/42FileChecker/42FileChecker.sh
read
clear

elif [ $var -eq 4 ];
then
open https://www.google.fr
read
clear

elif [ $var -eq 5 ];
then
find ~ -name "*.dSYM" -print -delete | find ~ -name 'a.out' -print -delete | find ~ -name '.DS_Store' -print -delete | find ~ -name '*.gch' -delete
echo "
Kill done."
read
clear

elif [ $var -eq 6 ];
then

####################GAME############################
win=0
let nb_myst="$RANDOM %100 + 0"
nb_try=10
while [ $nb_try -gt 0 ]
do
echo "Choisi un nombre entre 0 et 100 :  "
read try

if [ $try == "quit" ];
then
nb_try=10
break
fi

if [ $try -lt 0 ] || [ $try -gt 100 ];
then
echo "entre 0 et 100, lis les consignes.."
elif [ $try -ge 0 ] && [ $try -le 100 ];
then
if [ $try -gt $nb_myst ];
then
echo "Le nombre est plus petit."
let nb_try="$nb_try - 1"
echo "il te reste $nb_try essais.
"
elif [ $try -lt $nb_myst ];
then
echo "Le nombre est plus grand."
let nb_try="$nb_try - 1"
echo "il te reste $nb_try essais.
"
else [ $try=$nb_myst ]
echo "You Win Dude! Le nombre etait bien $nb_myst!"
win=101
nb_try=10
break
fi

else
echo "il te reste $nb_try essais.
"
fi

done
if [ $win -ne 101 ];
then
echo "T'as perdu! Il fallait trouver: $nb_myst"
fi
nb_try=10
read
clear
####################END GAME############################
elif [ $var -eq 101 ];
then
open https://www.le-101.fr
clear

else
echo "WHUUUT??"
read
clear
fi

done
